runtime: nodejs
env: flex

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
    
env_variables:
  HOST: '0.0.0.0'

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6
  target_concurrent_requests: 3

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10